export enum ViewsEnum {
  MAIN = 'VIEW_MAIN',
  BONDAGE = 'VIEW_BONDAGE',
  UNBONDAGE = 'VIEW_UNBONDAGE',
  QUERY = 'VIEW_QUERY',
  RESPONSE = 'VIEW_RESPONSE',
  ORACLES = 'VIEW_ORACLES',
  GET_ENDPOINT = 'VIEW_GET_ENDPOINT',
  INIT_CURVE = 'VIEW_INIT_CURVE',
  CREATE_PROVIDER = 'VIEW_CREATE_PROVIDER',
}
